### ISSUE TITLE
Highest Winstreak Display

### ISSUE THREAD

**Issue by Shaniquaniminiquani** [aymericingargiola/repentance-run-tracker#54] opened 2022-12-03 02:28 UTC
Have the highest winstreak save per rule and then display this pb next to the rule's current win streak. 
Example:
![image](https://user-images.githubusercontent.com/109847642/205417870-1837344d-a3f4-4499-b400-10753cae2fcf.png)

Basically the app would remember the highest streak for the specific characters and bosses assigned to a rule and then display a pb accordingly when that specific rule is used again. 

Ie. If I do a tLost to mother and beast streak, it will show a pb of 1 even though I've had a streak of 20 on isaac to the chest for instance and vice versa

Ps. It took me like 20 minutes to know what to title this lmao

**Comment by aymericingargiola** [comment] 2022-12-03 02:37
Yes, checking this !

**Comment by aymericingargiola** [comment] 2022-12-03 10:46
Update done to last release, i let you try https://github.com/aymericingargiola/repentance-run-tracker/releases/tag/v0.7.16

**Comment by Shaniquaniminiquani** [comment] 2022-12-04 18:59
![image](https://user-images.githubusercontent.com/109847642/205509774-74815b38-143c-4548-8a6a-3f31c3b473a3.png)
Have only gotten a chance to try it once, will continue trying for each char since I need to do mother and the beast with every char in this save file but I don't think it's working? Maybe I'm doing something wrong but think it should show at least 1 here

>(I changed icon for PB to crown and current to flag, makes more sense, same for the run killer with a crown instead of a flag)

This makes a lot of sense actually. Good change 👍

**Comment by aymericingargiola** [comment] 2022-12-04 19:04
> Have only gotten a chance to try it once, will continue trying for each char since I need to do mother and the beast with every char in this save file but I don't think it's working? Maybe I'm doing something wrong but think it should show at least 1 here

Oh it should works actually ! Can you give me your actual winStreaks.json and runs.json ?

**Comment by Shaniquaniminiquani** [comment] 2022-12-04 19:51
>i see in the second game you had a character switch, Isaac

Yeah I saw that too, don't really remember changing characters at all but maybe it was a modded interaction I'm not familiar with. No clue. 

Github was saying they didn't accept json files for upload for some reason but here is my latest backup which should be the same haha:
[backup_datas_12-04-22-024848PM_checked.zip](https://github.com/aymericingargiola/repentance-run-tracker/files/10149347/backup_datas_12-04-22-024848PM_checked.zip)

**Comment by aymericingargiola** [comment] 2022-12-04 20:35
@Shaniquaniminiquani

I see an other bug i just corrected, impossible to delete a winstreak 😨 

Also how was you able to add an other rule on the same save ? (it will conflict, what are exactly trying to do exactly ? You can select multiple characters on one streak rule)

Also that's strange it says your run isn't over with Cain, mod issue ?

I still continue to check the issue with this Magdaleine streak

**Comment by aymericingargiola** [comment] 2022-12-04 21:01
I made an update, you should remove the Cain winstreak, then click on edit and save on Magdalene winstreak, let me know !

**Comment by Shaniquaniminiquani** [comment] 2022-12-04 21:09
>Also how was you able to add an other rule on the same save ?

I wasn't originally allowed to so I decided to delete the previous mag rule to see if it worked on cain, but when I closed and restarted the app to give you the latest backup it pulled up both instead (Mag was already deleted) haha. Must be a bug.

>Also that's strange it says your run isn't over with Cain, mod issue ?

Its weird, I actually finished the run as dark judas like I said and the app didn't recognize it. It could be a mod issue, but I'm unsure. The weird thing is that it counted as a win towards the rule but I do see that the run is still ongoing on it

**Comment by aymericingargiola** [comment] 2022-12-04 21:14
> I wasn't originally allowed to so I decided to delete the previous mag rule to see if it worked on cain, but when I closed and restarted the app to give you the latest backup it pulled up both instead (Mag was already deleted) haha. Must be a bug.

Yes it is now fixed you can delete winstreaks now

> Its weird, I actually finished the run as dark judas like I said and the app didn't recognize it. It could be a mod issue, but I'm unsure. The weird thing is that it counted as a win towards the rule but I do see that the run is still ongoing on it

No dark juda doesn't impact, there is the date of the end of the run but we don't know if it's a win or a lose ahah, you can fix this later when you will start a new game on the same save, you can force the status of the run (delete, win or lose) from the improved broken runs pop up

**Comment by Shaniquaniminiquani** [comment] 2022-12-04 21:19
![image](https://user-images.githubusercontent.com/109847642/205516050-dde53f16-dab1-47df-ac89-d4d939488d8e.png)
I think the transformation is because of the chase sequence for keypiece 2. None of the other times I've done it I've gotten this. 

I also don't seem to have gotten an improve broken runs popup yet, but maybe after a few runs?
deleted the other streaks for save 2 but it didn't seem to fix the magdalene one, will try to make a new rule for a fresh character in a few

**Comment by aymericingargiola** [comment] 2022-12-04 21:30
>I think the transformation is because of the chase sequence for keypiece 2. None of the other times I've done it I've gotten this. My latest run shows 3, because I found a crawlspace and it behaves weird inside of there and transforms you twice

Ohhh nice catch ! I should ignore this character, when you are the lost, i should do a long debug session about this, thanks

> I also don't seem to have gotten an improve broken runs popup yet, but maybe after a few runs?

No i think in your case it's not showing because it triggers the end but only with the time... i don't know where comes from the issue, maybe the logs are altered with mds, but i'll add options so you can force mark the run as win or lose in the run's options.

> also even if dark judas doesn't impact the rule, it should still show that I transformed as him no?

It should not but i'll do more test since the id is different but if i remember well it does not count as new chararcter in the run

> deleted the other streaks for save 2 but it didn't seem to fix the magdalene one, will try to make a new rule for a fresh character in a few

Did you click on edit then click on save to update it ?

**Comment by Shaniquaniminiquani** [comment] 2022-12-05 00:57
Yeah thats odd, I went alt path and took both key pieces the next run and wasn't able to reproduce it either. It's probably a mod issue then for sure. Actually got a pretty weird bug were tjudas showed he started with bag of crafting on the app, and tcain looked like tjudas too. Super weird 
![image](https://user-images.githubusercontent.com/109847642/205527002-9fadde80-45d4-437a-89db-d428e766b305.png)
Tried doing Tmag to greedier as a rule and it still didn't tick up, this time there wasn't even a transformation though 😭
![image](https://user-images.githubusercontent.com/109847642/205527231-7ba079b3-51f7-4594-85d5-6f3966f76938.png)

**Comment by aymericingargiola** [comment] 2022-12-05 14:24
I saw you had issue about greed mode also before you edit, this is not the case anymore or caused by mods ? I can check this part while adding thoses buttons also, i'll check this later today !

**Comment by Shaniquaniminiquani** [comment] 2022-12-07 01:23
>I saw you had issue about greed mode also before your edit

After restarting the run the following tCain run seems to have tracked somewhat properly. I say somewhat because this time it tracked the characters and items properly without corrupting however I noticed the shop and ultra greed floor didn't track for some (They still counted as wins though so it wasn't a big deal, this could maybe be because I didn't pick up items in those floors (am unsure if I did or not) but usually the floors still show up, but empty haha):
![image](https://user-images.githubusercontent.com/109847642/206064211-7e68621d-a2bd-482b-a693-527495e8c3c2.png)

I don't have to do greedier for a bit but maybe f it was just a one time thing though, once I finish the beast mother runs I'll streak greedier w the tainted chars to check. 

Will try this tom and see if it tracks properly:
![image](https://user-images.githubusercontent.com/109847642/206062698-17ccb2c3-dfbb-42cc-95cb-48e151a7225f.png)

Sorry for the late reply haha, posted a [banger](https://www.reddit.com/r/bindingofisaac/comments/zdagu2/100_hours_never_seen_this_room_before_how_rare_is/) on reddit and then got sick so haven't had too much time to play 🙏

**Comment by aymericingargiola** [comment] 2022-12-07 07:13
>I say somewhat because this time it tracked the characters and items properly without corrupting however I noticed the shop and ultra greed floor didn't track for some 

It's strange indeed since it still finds the Greedier floor to validate the boss and the run, not sure what happenned, i should do some test and watch the game logs

> Will try this tom and see if it tracks properly:

Yes let me know ! Seems pretty strong rule

> posted a [banger](https://www.reddit.com/r/bindingofisaac/comments/zdagu2/100_hours_never_seen_this_room_before_how_rare_is/) on reddit

I don't really understand but everyone seems have fun ahah !

**Comment by Shaniquaniminiquani** [comment] 2022-12-09 16:53
>I'v added the option to edit run and force run status (win/lose) if then end trigger doesn't work for some reason

this works well 👍, is there a current way to check runs flagged as ongoing (Neither won or lost)?

**Comment by aymericingargiola** [comment] 2022-12-09 16:56
> is there a current way to check runs flagged as ongoing (Neither won or lost)?

I don't see any situation  where this could be necessary, you have an idea ? Because the runs watcher will not watch a run that has ended anymore

**Comment by Shaniquaniminiquani** [comment] 2022-12-09 17:04
I went back to fix the two broken runs that were still marked ongoing as cain but not corrupted and the idea crept up that there might be other runs I just hadn't noticed. I think this would only be useful if the ongoing run wasn't the latest run on that save file though

**Comment by aymericingargiola** [comment] 2022-12-09 17:09
> I went back to fix the two broken runs that were still marked ongoing as cain but not corrupted and the idea crept up that there might be other runs I just hadn't noticed. I think this would only be useful if the ongoing run wasn't the latest run on that save file though

Oh ok ! i though you wanted an option to mark the run as ongoing, yes i can add a filter in "win conditions"

**Comment by aymericingargiola** [comment] 2022-12-09 19:26
You can now check with last update ! https://github.com/aymericingargiola/repentance-run-tracker/releases/tag/v0.7.20

From your backup file i didn't find old runs with no end status 😄

**Closed** 2022-12-10 07:45 UTC
Labels: enhancement
