### ISSUE TITLE
Suggestions ranked by priority 

### ISSUE THREAD

**Issue by Shaniquaniminiquani** [aymericingargiola/repentance-run-tracker#38] opened 2022-08-02 14:54 UTC
Now that I'm back to doing 10-20 runs a day somewhat frequently I've come to use the application quite a lot haha, here are some suggestions I've come up with, some important, others more QOL ranked by importance in descending order.

1- Editing Streaks after they've been started. This is important in case a run corrupts, or you don't have the tracker open at the time, the runs won't account towards the winstreak. Overall controlling the streak number and conditions should be implemented. A current work around I believe exists is deleting the streak and starting a new one with a adjusted number (but then the prior runs won't be attached to the "current win streak") and also I've never actually gotten this function to work prior. An edit button would also fit right in on the empty space to the right of delete 
![image](https://user-images.githubusercontent.com/109847642/182398219-40431b52-07cc-4080-8243-50e29c583a41.png)
One additional note would be that it would be ideal to just match the winstreak on the game itself, but I'm unsure if this is able to be done currently, so I won't make it its own suggestion.

2- Be able to start the application mid run. This works _30% of the time_ currently I'd say, but official implementation for it would be blessed. A lot of the times I'll forget to run the app on my first run and have to start it in the starting room instead and it still won't work. At the very least the app should be made to not crash every time you enter a new floor if the run isn't being accounted for (since otherwise you're forced to close the app and have it happen again)

3- (BUG FIX (?)) I'm not entirely sure why this happens but whenever I finish a run or even am in the middle of a run, the items won't show up: 
![image](https://user-images.githubusercontent.com/109847642/182400876-12ce8488-fb64-4d68-861c-bf0f5b22bb85.png)
I have to manually scroll left for them to display. Which I find weird because this panning is not something you can even do manually
![image](https://user-images.githubusercontent.com/109847642/182401192-7c19779d-ce08-4be0-8664-ed2f09e65c0f.png)
the top is as far right as the app allows me to go, the bottom one is just to show that it does fix after moving far enough left

4- Adding the ability to sort through runs by run time. (I like going fast, would be appreciated to see what runs were the longest/ shortest)

5- Currently the pages only allow you to pick either the first 3 or the last page 
![image](https://user-images.githubusercontent.com/109847642/182403372-d46718ae-e421-4b7f-b044-be3eba929df9.png)
I'd suggest making it so that if you click the ellipsis an input box would show up allowing you to type a number so you can go straight to the page.

6- implementing an any ending rule. I really only go to blue baby but if I wanted to it would be nice to be able to go do mega satan or delirium instead as somewhat harder variants and still have the run count organically.

7- Think it would be nice to add more parameters to the search runs box. Most importantly item names, being able to see how many times you've started with tmtrainer for instance in your current win streak would be cool to see.

8- (BUG FIX) active items seem to be slightly bugged at times, not really priority but thought I'd bring it to your attention.
![image](https://user-images.githubusercontent.com/109847642/182402697-242429a3-be0b-4c8f-aa31-94d7071ca7d7.png)

I'm additionally leaving a copy of my latest backup here in case you need anything from it to replicate the bugs or check anything:
[backup_datas_08-02-22-104952AM.zip](https://github.com/aymericingargiola/repentance-run-tracker/files/9243261/backup_datas_08-02-22-104952AM.zip)
and this is the error dump from yesterday when starting the app during an ongoing run:
[repentance_run_tracker_error_dump-08-01-22-022047PM.zip](https://github.com/aymericingargiola/repentance-run-tracker/files/9243281/repentance_run_tracker_error_dump-08-01-22-022047PM.zip)

Thank you for your time 🙏

**Comment by aymericingargiola** [comment] 2022-08-02 20:07
Thanks for the feedback and ideas ! 

I am in hollidays currently till August 16th, so i'll be a bit busy during this time but i'll try to work on it if i have free time

1 - _"An edit button would also fit right in on the empty space to the right of delete"_ Yes i can totally do that, i have to check !
_"One additional note would be that it would be ideal to just match the winstreak on the game itself"_ I'm not sure if i get this, you mean the winstreak should be calculated on all the saves at the same time ? I could check that so i have to disable the possibility to add rules for different saves if this one is selected. Am i right ?

2 - I tested a lot this but maybe i have to check more, it's pretty difficult, i was working on it because the app or the game can crash at anytime, but i didn't really tested if we forget to run the tracker mid run, thanks

3 - I have to check this too, thanks

4 - Really nice idea !

5 - Yes i totally should a select to select a page manually !

6 - Ahhhh nice catch, i should check if at least the boss exist in the run and if it's a win, i should check this, i maybe missed something. It was the original idea indeed, i though it was working

7 - It could be very intensive to search for an item in every runs, every floors, or you only want items from the first floor ?

8 - It looks like it only broke with Glowing Hour Glass ? If so, i'm not sure i can fix this one at the moment, did you exeprienced this bug on other runs ?

**Comment by Shaniquaniminiquani** [comment] 2022-08-03 03:27
Np, hope you have a good time whatever you're doing in holidays. 

1- I meant it would be ideal for the tracker's winstreak to match the winstreak in game ie. atm I'm at 116 ws on save file 1
![image](https://user-images.githubusercontent.com/109847642/182517217-8f314203-90e2-4be4-81b0-4b1176382cc2.png)
 but on the tracker its only 
![image](https://user-images.githubusercontent.com/109847642/182517239-1c2ca765-497e-444f-a45b-e3b49c4c9abc.png)
So ideally it would just automatch in case you aren't always running the app. I'm unsure if it can gather this itself though without a mod or something

7- I think first floor only would work fine too, I'd mainly only use it to look for eden starts anyways :)

8- this doesn't just happen with glowing hourglass, I see it every now and then. Happened here too: 
![image](https://user-images.githubusercontent.com/109847642/182517018-8bc895f6-0fcc-43ac-88d9-7a77a6615386.png)
No backpack but its not really particularly an important fix

**Comment by aymericingargiola** [comment] 2022-08-03 06:45
Yes ok i see, yes it is not possible actually i think, even with LUA, but adding an edit button should fix your issue since you'll be able to manually change the number.

Ok strange i should check this about the multiple active items issue, something is maybe missing in the logs because it says when an active item is voided and a new active item is added so that's strange, if there was a code issue it would happens every time

**Comment by aymericingargiola** [comment] 2022-08-05 16:44
@Shaniquaniminiquani i comeback to the point "6", it looks like if you checked Blue Baby ("???") as last boss you can still do Mega Satan or Delirium and it will count the win, this isn't what you want ?

**Comment by Shaniquaniminiquani** [comment] 2022-08-05 17:40
So for instance if you got the delirium portal from the mom's foot fight and beat it, it would count as a blue baby victory? I've never tried it albeit I assumed it wouldn't work this way. Basically I just wanted a checkbox to count the win towards the streak as long as the run was won for the edge cases. If it already works this way then don't mind the suggestion I was unaware 🙏

**Comment by aymericingargiola** [comment] 2022-08-05 17:51
Ah yes you are right ! I have to check how to do that then, it will not works if you don't beat the boss you currently selected and if you beat delirium without beating blue baby it will not check. 
Do you know if it's valid from the streaking community if you don't beat your target but fight an harder boss ?

**Comment by Shaniquaniminiquani** [comment] 2022-08-05 18:29
I'm not entirely sure truthfully. Some people religiously stick to one ending while others have more lenient rulesets like just beating the game in general - any ending. Imo a harder path should count. Regardless of this I would still do blue baby first before a different ending like 100% of the time since I'm going for wr somewhat.

I hadn't yet tested whether or not doing fighting a different boss after the blue baby fight would make it count towards the tracker so that was mainly what I was inquiring about however. The way it works currently is fine 👍

**Comment by aymericingargiola** [comment] 2022-08-06 21:16
So from the 0.7.7 release some points should be fixed : 1, 2, 3 and 6 : https://github.com/aymericingargiola/repentance-run-tracker/releases/tag/v0.7.7

**Comment by Shaniquaniminiquani** [comment] 2022-08-07 06:02
![image](https://user-images.githubusercontent.com/109847642/183276547-ae32e2bb-8b15-4626-b5f7-bb0f1829094a.png)
Bless, editing works perfect 🙏. Took me a second to update because I was doing runs at the time.

I can only do real runs on stream for validity's sake so I'd only be able to extensively test tomorrow but from my quick testing with the console 2 seems to be completely fixed while 3 seems to have fixed but also introduce a new _different_ bug. Whenever you go down ~4 floors the current floor note seems to creep under the final boss note and you are unable to scroll it back to display the current floor
![image](https://user-images.githubusercontent.com/109847642/183276832-53251dc6-392d-4f97-a7d6-56e0d8d2c233.png)
Also I'm not sure if the blinking lines around the current floor is new or not (ongoing runs had always been bugged for me lmao) but it's a nice touch 👍

As for the accompanying mod, truthfully I've been using the tracker for about 9 months now so I was aware of its existence and I do actually like its functionality a lot, but no mods is a big core of streaking imo and although I believe non gameplay altering mods like External item descriptions etc are universally accepted, it's more of the principle for me. Would love to get the features on the standalone some time in the future (If the game were to ever allow it) but since you've gone through the trouble of making a specific mod for it, it's clear that it's not something that can be done without it currently 💀

Thanks for getting around to working on this on your holiday btw, was expecting this to come out later down the month

**Comment by aymericingargiola** [comment] 2022-08-07 08:20
Yes this was a bit rushed, i released an hotfix ! Let me know

https://github.com/aymericingargiola/repentance-run-tracker/releases/tag/v0.7.8

**Comment by Shaniquaniminiquani** [comment] 2022-08-07 17:11
My streak actually just died but the scrolling issue did seem to be fixed as well as the edited streak counter saving. Some additional things I've noticed now that I've lost is that the "best win streak" only counts the one with the most recorded tracker runs instead of the actual highest and also think it might be nice to print out the winstreak counter next to the deaths so if sorting by deaths you can see what numbers you died on (If that makes sense)

**Comment by aymericingargiola** [comment] 2022-08-07 17:45
Your streak died because of the update or you died in game ?

Yeah unfortunately the best winstreak will count what is on the tracker and do not know the adjust number, I don't really know at the moment how I will change that, same for showing the number of streak you had during your death, but I maybe have some ideas 🤔

**Comment by Shaniquaniminiquani** [comment] 2022-08-08 13:42
I died in game, will do though!

**Comment by aymericingargiola** [comment] 2022-08-12 18:41
Everything you asked should be done now ! https://github.com/aymericingargiola/repentance-run-tracker/releases/tag/v0.7.11

Except number 8, i'm not sure how to reproduce it, but maybe if it happens again, can you send me your game logs so i can replay and debug your game ? It should be in `C:\Users\[YOUR NAME]\Documents\my games\Binding of Isaac Repentance\log.txt`

**Closed by aymericingargiola** 2022-08-12 18:41 UTC
Labels: enhancement

**Comment by Shaniquaniminiquani** [comment] 2022-08-13 05:56
Will do if I notice 8 happen again, it's not very common albeit so thats a good thing

As for the custom item search, would it be possible to drop the first colon so it's "item:51:2" instead of ":item:51:2"? I thought the first colon was to specify a character but "isaac:item:51:2" doesn't seem to work + you can tech already sort by character. 
Or alternatively drop the ":item:" scheme altogether and just input "51:2"/ "Pentagram:2"? I don't believe typing in numbers alone/ item names would conflict with other current search query's unless theres plan to expand in the future 

I read the patch notes so I'd be able to use it but I think the functionality might be lost on anyone who doesn't already know it exists since the specific phrasing isn't very intuitive to reproduce. This is more of a low priority Qol change though, so no worries if it's outside of scope. Overall am really happy with the changes, a lot has been done this past month haha

**Comment by aymericingargiola** [comment] 2022-08-13 06:10
The first ":" is to tell the search box function that this is a query and so directly bypass the basic text search, i'v updated the readme also, and I'll keep updating as soon as I add things like this ! The main idea is maybe later to have other custom queries like :monster:[id]:[floor], whatever people wants :)
Also gulped trinkets and items have conflict id's so it's interesting to keep ":item:" so we know what we search, maybe later we can have gulped trinkets query, what do you think ?

I can later make a new easy query builder filter component with an UI instead to do this in the search box (Wich will takes time to build ahah)

Yeah thank you for all your feedbacks, I can't really test every situations or miss important / qol features !

**Comment by Shaniquaniminiquani** [comment] 2022-08-13 06:41
A gulped trinket query would be interesting, I think since it would have significantly less things to search for it could potentially search every floor instead. One simple way to eliminate dud searches is to only search runs that actually have a gulped trinket by giving them a special identifier at the end of the run. Ie, you might have 500 recorded runs but this would only need to scan like 20 or so that have the gulped label. This would eliminate the need to search for trinkets by floor altogether. Also since it's more niche the default query could be still used for items ie "51:2" while trinkets would have their own "trinket:51". Would this allow tracking for golden trinket variants as well? Im unsure how those are specifically handled in code.

An UI feature would definitely fix all of this as well for sure though. I think if we go this route it might be smart to also have options for turning on or off certain features like for instance the characters and search from starting date to ending date query. I hardly ever use these if at all but they do make the current ui take 2 lines vertically 
![image](https://user-images.githubusercontent.com/109847642/184471811-b3da1400-d884-4406-9206-119fc6404f27.png)
If you were to have one single search ui that accepted specific parameters it would make for a cleaner app for sure

I think one back of the napkin change I thought of was to have eden starting stats be displayed on the tracker. Iirc his stats should be linked to the seed so there might be a way to do this without a mod potentially since they would be the same every time. The way I'd envision it if it was possible would be to have it be where the end stats are displayed if you use the mod and either click on them to switch between the end and starting stats or have a option in the configure menu on which should be displayed by default. I'm unsure if the technology is there yet for this implementation though. In the worst case scenario it might mean having to reverse engineer the seed to see the stats/ running a smaller separate instance of the game to scrape the stats.
Either way it could be a good idea for the modded side of the app nonetheless if not possible to do unmodded 👍

**Comment by aymericingargiola** [comment] 2022-08-13 06:56
I have to check about golden trinkets but if I remember correctly they have their own IDs and I support them yes, I made something about golden trinkets ! I have to add a flag to runs with gulped trinkets then yes, I have to check to do this on previous runs also.

This is a good idea to keep starting stats of Eden ! But yeah unfortunately with the mod it's hardly possible unless I add an option to add manually starting stats and end stats wich is not very convenient.

I'll add option to hide/show filters yeah that's a nice point
